/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appparqueadero;

/**
 *
 * @author Admin
 */
public class InicioApp extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InicioApp.class.getName());

    /**
     * Creates new form Principal
     */
    public InicioApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Inicio = new javax.swing.JPanel();
        jLabel_NombreApp = new javax.swing.JLabel();
        jLabel_LogoApp = new javax.swing.JLabel();
        button_IngrVehiculo = new java.awt.Button();
        button_RetVehiculo = new java.awt.Button();
        button_ListVehiculos = new java.awt.Button();
        button_Salir = new java.awt.Button();
        jLabel_SubtituloApp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Inicio.setBackground(new java.awt.Color(0, 83, 103));
        jPanel_Inicio.setForeground(new java.awt.Color(255, 255, 255));
        jPanel_Inicio.setMinimumSize(new java.awt.Dimension(320, 400));
        jPanel_Inicio.setPreferredSize(new java.awt.Dimension(320, 400));
        jPanel_Inicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_NombreApp.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel_NombreApp.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_NombreApp.setText("ParkZone");
        jPanel_Inicio.add(jLabel_NombreApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jLabel_LogoApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appparqueadero/Imagenes/Logo auto.png"))); // NOI18N
        jPanel_Inicio.add(jLabel_LogoApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 150, 102));

        button_IngrVehiculo.setBackground(new java.awt.Color(0, 153, 153));
        button_IngrVehiculo.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        button_IngrVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        button_IngrVehiculo.setLabel("Ingresar vehiculo");
        button_IngrVehiculo.addActionListener(this::button_IngrVehiculoActionPerformed);
        jPanel_Inicio.add(button_IngrVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 140, 50));

        button_RetVehiculo.setBackground(new java.awt.Color(0, 153, 153));
        button_RetVehiculo.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        button_RetVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        button_RetVehiculo.setLabel("Retirar vehiculo");
        jPanel_Inicio.add(button_RetVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 140, 50));

        button_ListVehiculos.setBackground(new java.awt.Color(0, 153, 153));
        button_ListVehiculos.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        button_ListVehiculos.setForeground(new java.awt.Color(255, 255, 255));
        button_ListVehiculos.setLabel("Lista de vehiculos");
        jPanel_Inicio.add(button_ListVehiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 140, 50));

        button_Salir.setBackground(new java.awt.Color(255, 51, 51));
        button_Salir.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        button_Salir.setForeground(new java.awt.Color(255, 255, 255));
        button_Salir.setLabel("Salir");
        jPanel_Inicio.add(button_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 140, 50));

        jLabel_SubtituloApp.setFont(new java.awt.Font("Segoe UI Semibold", 2, 16)); // NOI18N
        jLabel_SubtituloApp.setForeground(new java.awt.Color(51, 255, 255));
        jLabel_SubtituloApp.setText("App para control de estacionamiento");
        jPanel_Inicio.add(jLabel_SubtituloApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        getContentPane().add(jPanel_Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_IngrVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_IngrVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_IngrVehiculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InicioApp().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button_IngrVehiculo;
    private java.awt.Button button_ListVehiculos;
    private java.awt.Button button_RetVehiculo;
    private java.awt.Button button_Salir;
    private javax.swing.JLabel jLabel_LogoApp;
    private javax.swing.JLabel jLabel_NombreApp;
    private javax.swing.JLabel jLabel_SubtituloApp;
    private javax.swing.JPanel jPanel_Inicio;
    // End of variables declaration//GEN-END:variables
}
