/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package appparqueadero;

/**
 *
 * @author Admin
 */
public class Panel_IngresarVehiculo extends javax.swing.JPanel {

    /**
     * Creates new form Ingresar_Vehiculo
     */
    public Panel_IngresarVehiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        button1 = new java.awt.Button();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(360, 370));
        setPreferredSize(new java.awt.Dimension(360, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 66, 107));
        jLabel1.setText("Ingreso de vehiculos al estacionamiento");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 350, 30));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(15, 102, 126));
        jLabel2.setText("Tipo de vehiculo:");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 140, -1));

        jTextField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 210, 30));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(15, 102, 126));
        jLabel3.setText("Placa:");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 250, 30));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(15, 102, 126));
        jLabel4.setText("Propietario:");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 100, -1));

        jRadioButton1.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jRadioButton1.setText("Auto");
        jRadioButton1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jRadioButton1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jRadioButton1.addActionListener(this::jRadioButton1ActionPerformed);
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, 20));

        jRadioButton2.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jRadioButton2.setText("Motocicleta");
        jRadioButton2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jRadioButton2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jRadioButton2.addActionListener(this::jRadioButton2ActionPerformed);
        add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, 20));

        button1.setBackground(new java.awt.Color(15, 102, 126));
        button1.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setLabel("Registrar");
        button1.addActionListener(this::button1ActionPerformed);
        add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 120, 40));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 340, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
